// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform - '
      'you can reconfigure this by running the FlutterFire CLI again.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAkTwFG_Q2zdmE4KvxswFbUOJOqaVKVo4',
    appId: '1:1011595776145:web:5b858ee33d1887b2572f30',
    messagingSenderId: '1011595776145',
    projectId: 'digital-menu-prod-2026',
    authDomain: 'digital-menu-prod-2026.firebaseapp.com',
    storageBucket: 'digital-menu-prod-2026.firebasestorage.app',
  );
}
