import 'dart:typed_data';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../menu/domain/entities/dish.dart';
import '../../../menu/domain/usecases/add_dish_usecase.dart';
import '../../../menu/domain/usecases/upload_dish_image_usecase.dart';
import '../../../menu/domain/usecases/update_dish_usecase.dart';
import '../../../menu/domain/usecases/delete_dish_usecase.dart';
import 'admin_dish_state.dart';

class AdminDishCubit extends Cubit<AdminDishState> {
  final AddDishUseCase _addDishUseCase;
  final UploadDishImageUseCase _uploadDishImageUseCase;
  final UpdateDishUseCase _updateDishUseCase;
  final DeleteDishUseCase _deleteDishUseCase;

  AdminDishCubit({
    required AddDishUseCase addDishUseCase,
    required UploadDishImageUseCase uploadDishImageUseCase,
    required UpdateDishUseCase updateDishUseCase,
    required DeleteDishUseCase deleteDishUseCase,
  })  : _addDishUseCase = addDishUseCase,
        _uploadDishImageUseCase = uploadDishImageUseCase,
        _updateDishUseCase = updateDishUseCase,
        _deleteDishUseCase = deleteDishUseCase,
        super(const AdminDishState.initial());

  Future<void> createDish({
    required String name,
    required double price,
    required String categoryId,
    required String fileName,
    required Uint8List fileBytes,
  }) async {
    emit(const AdminDishState.loading());

    // 1. Upload/Convert the image
    final uploadResult = await _uploadDishImageUseCase(fileName, fileBytes);
    if (!uploadResult.isSuccess || uploadResult.data == null) {
      emit(AdminDishState.error(uploadResult.message));
      return;
    }

    final downloadUrl = uploadResult.data!;

    // 2. Save the dish to Firestore
    final dish = Dish(
      id: '', // Generated by Firestore
      name: name,
      price: price,
      photoUrl: downloadUrl,
      categoryId: categoryId,
      createdAt: DateTime.now().millisecondsSinceEpoch,
    );

    final saveResult = await _addDishUseCase(dish);
    if (saveResult.isSuccess) {
      emit(const AdminDishState.success());
    } else {
      emit(AdminDishState.error(saveResult.message));
    }
  }

  Future<void> editDish({
    required String id,
    required String name,
    required double price,
    required String categoryId,
    String? fileName,
    Uint8List? fileBytes,
    required String existingPhotoUrl,
    int? existingCreatedAt,
  }) async {
    emit(const AdminDishState.loading());

    String photoUrl = existingPhotoUrl;

    // 1. If a new image was picked, upload/convert it
    if (fileName != null && fileBytes != null) {
      final uploadResult = await _uploadDishImageUseCase(fileName, fileBytes);
      if (!uploadResult.isSuccess || uploadResult.data == null) {
        emit(AdminDishState.error(uploadResult.message));
        return;
      }
      photoUrl = uploadResult.data!;
    }

    // 2. Update the dish in Firestore
    final dish = Dish(
      id: id,
      name: name,
      price: price,
      photoUrl: photoUrl,
      categoryId: categoryId,
      createdAt: existingCreatedAt ?? DateTime.now().millisecondsSinceEpoch,
    );

    final result = await _updateDishUseCase(dish);
    if (result.isSuccess) {
      emit(const AdminDishState.success());
    } else {
      emit(AdminDishState.error(result.message));
    }
  }

  Future<void> deleteDish(String dishId) async {
    emit(const AdminDishState.loading());
    final result = await _deleteDishUseCase(dishId);
    if (result.isSuccess) {
      emit(const AdminDishState.success());
    } else {
      emit(AdminDishState.error(result.message));
    }
  }

  void reset() {
    emit(const AdminDishState.initial());
  }
}
